### PR TITLE
fix publish error

### PR DESCRIPTION
**Pull request by ycdawn**
fix rospy.loginfo("filename",filename) error ,  fix tf publish only once because rospy.spin() does not work since there is no Callback function.

### CODE REVIEW

**Comment by marcoesposito1988** [comment]
Excellent, thanks for the contribution!

**Comment by marcoesposito1988** [comment]
On a second thought: `tf_static` is supposed to be latched, so this should actually work: even if a node is connected after the message is published, they should get the transform and add it to `tf`. The transform should be valid for an indefinite amount of time, so there should be no need to publish it again.

Did you have any issue that lead you to this change?

**Comment by ycdawn** [comment]
> On a second thought: `tf_static` is supposed to be latched, so this should actually work: even if a node is connected after the message is published, they should get the transform and add it to `tf`. The transform should be valid for an indefinite amount of time, so there should be no need to publish it again.
> 
> Did you have any issue that lead you to this change?
I can't get tf transform continually 2 days ago , so I change the code, but I test it today, it works! You are right ,`tf_static` just need to publish once, I will colse this pull requset.

**Comment by ycdawn** [comment]
I can't get tf transform continually 2 days ago , so I change the code, but I test it today, it works! You are right ,tf_static just need to publish once, I will colse this pull requset.

**Pull request closed without merging**
