### PR TITLE
Run catkin_lint on packages

### PR DESCRIPTION
**Pull request by aPonza**
Wanting to follow up on [my comment](https://github.com/IFL-CAMP/easy_handeye/issues/1#issuecomment-509984232) I started with running `catkin_lint`, and then encountered error `catkin ValueError: Set of coroutines/Futures is empty.` which stems from the circular dependency introduced by adding the `exec_depend` from the comment.

I thought I'd still at least let you know about these commits while thinking about the former issue.

### CODE REVIEW

**Comment by aPonza** [comment]
Regarding the circular dependency, I've found [this issue](https://github.com/catkin/catkin_tools/issues/523) explaining there ought to be architectural changes or maybe a switch to package format 3, which are both weird.

I'd much rather remove the `<exec_depend>easy_handeye</exec_depend>` from rqt_easy_handeye's package.xml though. I didn't see issues while trying it out actually, what do you think?

**Comment by aPonza** [comment]
I had not seen [this line](https://github.com/IFL-CAMP/easy_handeye/blob/1e8a19032126cf7370db9168bcffb2242c23c855/rqt_easy_handeye/src/rqt_easy_handeye/rqt_easy_handeye.py#L7) so the above commit is fundamentally wrong.

**Comment by marcoesposito1988** [comment]
Yes, rqt_easy_handeye is thought as a GUI for easy_handeye, so it depends from it (and that is the reason why it is also listed as a dependency in its package.xml).

Now it actually does make sense that you include rqt_easy_handeye in your own package.xml, since you depend on it. Maybe I should document this.

**Comment by aPonza** [comment]
The problem is the dependency is hidden, in a way, because I'm not the one using it, it's easy_handeye that's using it (as a GUI): I'm calling `roslaunch easy_handeye calibrate.launch` which should be working on its own provided I compiled easy_handeye. It's more of an internal component of easy_handeye, don't you think?

**Comment by marcoesposito1988** [comment]
Yes, absolutely! I'll find a way to rework it.

**Comment by aPonza** [comment]
What do you think about the catkin_lint commits? Should I revert 7d409a8 so you can merge those two or would you rather edit/discard them?

**Comment by marcoesposito1988** [comment]
If you could do a rebase interactive and remove that commit I'd be glad to merge the lint commits!

The more I think about the dependency problem, the more appealing it seems to move the launch files to the rqt package to avoid the circular dependency. It should make everything smooth and linear.

**Comment by marcoesposito1988** [comment]
Thanks a lot!

**Pull request merged**
