### PR TITLE
Complete tf2 transition

### PR DESCRIPTION
**Pull request by aPonza**
I don't particularly like how handeye_calibrator came out, but it does seem to be correctly converted. Many things were not needed anymore, but the diff doesn't really pick the changes up correctly.

Also of note is the fact that now it seems every time one takes the n-th sample there's 2n deep copies happening (it probably was the same way before as well but the package wasn't printing `deep copy` with each sample).

And I also couldn't find an alternative to `tf.transformations` for rqt_calibrationmovements.py

### CODE REVIEW

**Comment by aPonza** [comment]
BTW it seems this fixes some kind of `leak` I was having as it's not showing anymore. See https://github.com/ros-visualization/rviz/issues/1386

**Comment by marcoesposito1988** [comment]
The leak thingy is interesting.. have you tried just switching to the tf2 static_transform_publisher?

I was actually doing the transition myself in the development branch. Would you feel like taking a look at it and integrate those changes?

**Comment by marcoesposito1988** [comment]
I am closing this pull request, since I merged the development branch. But thank you anyway for the effort! Any further proposal for improvement is welcome and encouraged.

**Comment by aPonza** [comment]
Cheers, couldn't get to it on time, thank you for taking care of it!

**Pull request closed without merging**
